'use client';

import { motion } from 'framer-motion';
import { Share2, Download, Copy, Check } from 'lucide-react';
import { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { CareerProfile } from '@/lib/types';
import { getTriggerLabel } from '@/lib/profile/generator';

interface ProfileCardProps {
  profile: CareerProfile;
  userName: string;
  headline: string;
}

export function ProfileCard({ profile, userName, headline }: ProfileCardProps) {
  const [copied, setCopied] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const careerAnchorDescriptions: Record<string, string> = {
    'autonomy': 'Values independence and freedom',
    'security': 'Values stability and predictability',
    'technical': 'Values deep expertise and mastery',
    'managerial': 'Values leadership and influence',
    'entrepreneurial': 'Values creation and building',
    'service': 'Values purpose and helping others',
    'challenge': 'Values solving hard problems',
    'lifestyle': 'Values balance and flexibility'
  };

  const hollandDescriptions: Record<string, string> = {
    'R': 'Realistic - Practical & hands-on',
    'I': 'Investigative - Analytical & curious',
    'A': 'Artistic - Creative & expressive',
    'S': 'Social - Helping & teaching',
    'E': 'Enterprising - Leading & persuading',
    'C': 'Conventional - Organized & detail-oriented'
  };

  const copyToClipboard = async () => {
    const text = `
${userName}'s Career Profile

"${headline}"

Career Type: ${profile.psychology.careerAnchor.primary.replace('_', ' ')} - ${careerAnchorDescriptions[profile.psychology.careerAnchor.primary] || ''}
Work Style: ${profile.psychology.holland.code} (${profile.psychology.holland.primary ? hollandDescriptions[profile.psychology.holland.primary] : ''})
Primary Need: ${profile.psychology.sdt.primaryUnmetNeed || 'Balanced'}

What's Driving Change:
${profile.trigger.map(t => '• ' + getTriggerLabel(t)).join('\n')}

Generated by NextStep - nextstep.app
    `.trim();
    
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadAsImage = async () => {
    if (!cardRef.current) return;
    
    // Using html2canvas would be ideal here, but for MVP we'll use the copy function
    // In production, you'd add: const canvas = await html2canvas(cardRef.current);
    copyToClipboard();
  };

  return (
    <div className="space-y-4">
      <div 
        ref={cardRef}
        className="relative p-8 rounded-2xl bg-gradient-to-br from-primary/10 via-background to-accent/10 border-2 border-primary/20 overflow-hidden"
      >
        {/* Background pattern */}
        <div className="absolute inset-0 opacity-5">
          <div className="absolute inset-0" style={{
            backgroundImage: `radial-gradient(circle at 2px 2px, currentColor 1px, transparent 0)`,
            backgroundSize: '24px 24px'
          }} />
        </div>

        <div className="relative">
          {/* Header */}
          <div className="text-center mb-6">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 text-2xl mb-3">
              {userName.charAt(0).toUpperCase()}
            </div>
            <h3 className="text-xl font-bold">{userName}&apos;s Career Profile</h3>
            <p className="text-sm text-muted-foreground mt-1 italic">
              &ldquo;{headline}&rdquo;
            </p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-2 gap-4 mb-6">
            <div className="p-3 rounded-lg bg-background/60 backdrop-blur text-center">
              <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">Career Type</p>
              <p className="font-semibold capitalize">
                {profile.psychology.careerAnchor.primary.replace('_', ' ')}
              </p>
              <p className="text-xs text-muted-foreground mt-0.5">
                {careerAnchorDescriptions[profile.psychology.careerAnchor.primary]}
              </p>
            </div>

            <div className="p-3 rounded-lg bg-background/60 backdrop-blur text-center">
              <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">Work Style</p>
              <p className="font-semibold font-mono">{profile.psychology.holland.code}</p>
              <p className="text-xs text-muted-foreground mt-0.5">
                {profile.psychology.holland.primary ? hollandDescriptions[profile.psychology.holland.primary]?.split(' - ')[0] : 'Mixed'}
              </p>
            </div>

            <div className="p-3 rounded-lg bg-background/60 backdrop-blur text-center">
              <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">Primary Need</p>
              <p className="font-semibold capitalize">
                {profile.psychology.sdt.primaryUnmetNeed || 'Balanced'}
              </p>
            </div>

            <div className="p-3 rounded-lg bg-background/60 backdrop-blur text-center">
              <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">Priority</p>
              <p className="font-semibold capitalize">
                {profile.priority || 'Exploring'}
              </p>
            </div>
          </div>

          {/* Triggers */}
          <div className="p-3 rounded-lg bg-background/60 backdrop-blur">
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-2 text-center">What&apos;s Driving Change</p>
            <div className="flex flex-wrap justify-center gap-2">
              {profile.trigger.slice(0, 3).map((t) => (
                <span 
                  key={t} 
                  className="px-2 py-1 text-xs rounded-full bg-primary/10 text-primary"
                >
                  {getTriggerLabel(t)}
                </span>
              ))}
            </div>
          </div>

          {/* Footer */}
          <div className="mt-6 text-center">
            <p className="text-xs text-muted-foreground">
              Generated by <span className="font-semibold">NextStep</span>
            </p>
          </div>
        </div>
      </div>

      {/* Share Actions */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="flex justify-center gap-2"
      >
        <Button 
          variant="outline" 
          size="sm"
          onClick={copyToClipboard}
        >
          {copied ? (
            <>
              <Check className="w-4 h-4 mr-2 text-green-500" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4 mr-2" />
              Copy
            </>
          )}
        </Button>
        <Button 
          variant="outline" 
          size="sm"
          onClick={downloadAsImage}
        >
          <Download className="w-4 h-4 mr-2" />
          Save
        </Button>
        <Button 
          variant="outline" 
          size="sm"
          onClick={() => {
            if (navigator.share) {
              navigator.share({
                title: `${userName}'s Career Profile`,
                text: `Check out my career profile on NextStep`,
                url: window.location.href
              });
            } else {
              copyToClipboard();
            }
          }}
        >
          <Share2 className="w-4 h-4 mr-2" />
          Share
        </Button>
      </motion.div>
    </div>
  );
}

